import psycopg2
from psycopg2 import Error

def create_func(query):
    try:
        connection = psycopg2.connect(
            host='localhost', 
            database='PhoneBook',
            user='postgres',
            password='zhuka'
            )
        cursor = connection.cursor()
        cursor.execute(query)
        connection.commit()

    except (Exception, Error) as error:
        print("Ошибка при работе с PostgreSQL", error)
    finally:
        if connection:
            cursor.close()
            connection.close()
            print('Procedure is created')

postgresql_proc = """
CREATE OR REPLACE PROCEDURE delete_user(n_username text) 
AS $$ 
BEGIN
    DELETE FROM phonebook WHERE username = n_username;
END;
$$ 
LANGUAGE plpgsql
"""
create_func(postgresql_proc)


del_name = input()
try:
    # Подключиться к существующей базе данных
    connection = psycopg2.connect(
        host='localhost', 
        database='PhoneBook',
        user='postgres',
        password='zhuka'
    )

    cursor = connection.cursor()
    cursor.execute('CALL delete_user(%s)', (del_name,))
    connection.commit()

except (Exception, Error) as error:
    print("ERROR", error)
finally:
    if connection:
        print("User is deleted!")
        cursor.close()
        connection.close()
